[shoumitro@android123 ~]$ pip list
Package                      Version 
---------------------------- --------
anytree                      2.8.0   
appdirs                      1.4.3   
application-utility          1.3.1   
asgiref                      3.2.3   
attrs                        20.1.0  
autobahn                     20.7.1  
Automat                      20.2.0  
bottle                       0.12.18 
btrfsutil                    1.1.1   
CacheControl                 0.12.6  
catfish                      1.4.13  
cffi                         1.14.2  
channels                     2.4.0   
chardet                      3.0.4   
cheroot                      8.2.1   
CherryPy                     18.5.0  
Click                        7.0     
colorama                     0.4.3   
constantly                   15.1.0  
contextlib2                  0.6.0   
cryptography                 3.0     
cupshelpers                  1.0     
daphne                       2.5.0   
distlib                      0.3.0   
distro                       1.4.0   
Django                       3.0.1   
docopt                       0.6.2   
filelock                     3.0.12  
Flask                        1.1.1   
gufw                         19.10.0 
html5lib                     1.0.1   
hupper                       1.9.1   
hyperlink                    20.0.1  
idna                         2.9     
importlib-metadata           1.5.0   
incremental                  17.5.0  
isc                          2.0     
itsdangerous                 1.1.0   
Jade-Application-Kit         2.1.3   
jaraco.classes               3.1.0   
jaraco.collections           3.0.0   
jaraco.functools             3.0.0   
jaraco.text                  3.2.0   
Jinja2                       2.10.3  
keyutils                     0.6     
lensfun                      0.3.95  
lightdm-gtk-greeter-settings 1.2.2   
lockfile                     0.12.2  
louis                        3.13.0  
lxml                         4.5.0   
MarkupSafe                   1.1.1   
menulibre                    2.2.1   
mod-pywebsocket              0.7.9   
mod-wsgi                     4.7.0   
mod-wsgi-httpd               2.4.41.1
more-itertools               8.2.0   
msgpack                      0.6.2   
mugshot                      0.4.2   
mysql-connector-python       8.0.18  
mysqlclient                  2.0.1   
npyscreen                    4.10.5  
ordered-set                  3.1.1   
packaging                    20.2    
pacman-mirrors               4.16.4  
PasteDeploy                  2.0.1   
pep517                       0.8.1   
pexpect                      4.8.0   
Pillow                       6.2.1   
pip                          19.3.1  
plaster                      1.0     
plaster-pastedeploy          0.7     
ply                          3.11    
portend                      2.6     
progress                     1.5     
protobuf                     3.11.2  
psutil                       5.7.0   
ptyprocess                   0.6.0   
py-mysql                     1.0     
pyasn1                       0.4.8   
pyasn1-modules               0.2.8   
pycairo                      1.19.1  
pycparser                    2.20    
pycups                       1.9.74  
pycurl                       7.43.0.5
Pygments                     2.5.2   
PyGObject                    3.34.0  
PyHamcrest                   2.0.2   
pyOpenSSL                    19.1.0  
pyparsing                    2.4.6   
PyQt5                        5.14.1  
PyQt5-sip                    12.7.1  
PyQtWebEngine                5.14.0  
pyramid                      1.10.4  
python-distutils-extra       2.39    
pytoml                       0.1.21  
pytz                         2019.3  
pyxdg                        0.26    
PyYAML                       5.3     
reportlab                    3.5.34  
requests                     2.23.0  
retrying                     1.3.3   
service-identity             18.1.0  
setuptools                   45.2.0  
sip                          4.19.21 
six                          1.14.0  
sqlparse                     0.3.0   
SSSDConfig                   2.2.3   
team                         1.0     
tempora                      2.0.0   
toml                         0.10.0  
tornado                      6.0.3   
translationstring            1.3     
Twisted                      20.3.0  
txaio                        20.4.1  
udiskie                      2.1.0   
ufw                          0.36    
urllib3                      1.25.8  
venusian                     3.0.0   
webencodings                 0.5.1   
WebOb                        1.8.5   
Werkzeug                     0.16.0  
youtube-dl                   2020.3.6
zc.lockfile                  2.0     
zipp                         3.1.0   
zope.deprecation             4.4.0   
zope.interface               4.7.1   
