# Generated by Django 3.0.1 on 2020-09-24 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalItem', models.IntegerField(default=0)),
                ('totalTaxed', models.FloatField(default=0.0, max_length=20)),
                ('discount', models.FloatField(default=0.0, max_length=20)),
                ('deliveryCost', models.FloatField(default=0.0, max_length=20)),
                ('totalCost', models.FloatField(default=0.0, max_length=20)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddr',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addr_title', models.CharField(max_length=255)),
                ('p_name', models.CharField(max_length=255)),
                ('p_phone', models.CharField(max_length=255)),
                ('p_addr1', models.CharField(max_length=255)),
                ('p_addr2', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('amount', models.FloatField(max_length=20)),
            ],
            options={
                'verbose_name': 'Delivery Address',
                'verbose_name_plural': 'Delivery Addresses',
                'db_table': 'DeliveryAddr',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discountRate', models.FloatField(max_length=20)),
                ('isActive', models.BooleanField()),
                ('startDate', models.DateTimeField()),
                ('expirationDate', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Discount',
                'verbose_name_plural': 'Discounts',
                'db_table': 'Discount',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalItem', models.IntegerField(default=0)),
                ('totalTaxed', models.FloatField(default=0.0, max_length=20)),
                ('discount', models.FloatField(default=0.0, max_length=20)),
                ('deliveryCost', models.FloatField(default=0.0, max_length=20)),
                ('totalCost', models.FloatField(default=0.0, max_length=20)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('submitted_at', models.CharField(max_length=225)),
                ('shippingSlot', models.CharField(max_length=225)),
                ('shippingMethod', models.CharField(max_length=225)),
                ('note', models.CharField(max_length=225)),
                ('onlinePayment', models.CharField(max_length=225)),
            ],
            options={
                'verbose_name': 'Order Information',
                'verbose_name_plural': 'Order Informations',
                'db_table': 'OrderInfo',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=225)),
                ('isPaid', models.CharField(max_length=225)),
                ('deliveryAddr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.DeliveryAddr')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Invoice')),
                ('orderInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.OrderInfo')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=5000)),
                ('weight', models.CharField(max_length=255)),
                ('brand', models.CharField(choices=[('Brand', 'Brand'), ('No Brand', 'NO Brand')], max_length=100)),
                ('stock', models.IntegerField()),
                ('currentStock', models.IntegerField()),
                ('price', models.FloatField(max_length=20)),
                ('unitPrice', models.FloatField(max_length=20)),
                ('taxed', models.FloatField(default=0.0, max_length=20)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Discount')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'Product',
                'ordering': ('id', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('postcode', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'Users',
                'ordering': ('email',),
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc1', models.CharField(max_length=255)),
                ('desc2', models.CharField(max_length=255)),
                ('desc3', models.CharField(max_length=255)),
                ('desc4', models.CharField(max_length=255)),
                ('image1', models.ImageField(upload_to='product')),
                ('image2', models.ImageField(upload_to='product')),
                ('image3', models.ImageField(upload_to='product')),
                ('image4', models.ImageField(upload_to='product')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='public.Product')),
            ],
            options={
                'verbose_name': 'Product Information',
                'verbose_name_plural': 'Product Informations',
                'db_table': 'ProductInfo',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Category')),
            ],
            options={
                'verbose_name': 'ProductCategory',
                'verbose_name_plural': 'ProductCategories',
                'db_table': 'ProductCategory',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.ProductCategory'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField(max_length=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Orders')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'Payment',
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Users'),
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('u_password', models.CharField(max_length=100)),
                ('u_re_password', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Users')),
            ],
            options={
                'verbose_name': 'Login',
                'verbose_name_plural': 'Logins',
                'db_table': 'Login',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalCost', models.FloatField(max_length=20)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Users')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
                'db_table': 'InvoiceItem',
            },
        ),
        migrations.AddField(
            model_name='deliveryaddr',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Invoice'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('totalCost', models.FloatField(max_length=20)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Users')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'CartItem',
            },
        ),
    ]
